name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
        sudo apt update && sudo apt install -y libpcap-dev
        go build -v ./... 
        make releases 
        ls bin/* -l
        
    - name: Upload linux build
      uses: actions/upload-artifact@v3
      with:
        name: phantomsocks_linux_rawsocket
        path: bin/phantomsocks-linux* 
        
    - name: Upload windows build
      uses: actions/upload-artifact@v3
      with:
        name: phantomsocks_win_windivert
        path: bin/phantomsocks-windows*
   
